apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: se-spring-boot
  name: se-spring-boot
  namespace: se-spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: se-spring-boot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: se-spring-boot
    spec:
      containers:
      - image: tanzuharbor.tanzu.lab/app-images/pet-clinic@sha256:3aacb4ce04febfb74c94ffce1b2a2a18bbbbd9f35489904ce6475d6d7c181608
        name: pet-clinic
        resources: {}
status: {}
