apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: se-spring-boot
  name: se-spring-boot
  namespace: se-spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: se-spring-boot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: se-spring-boot
    spec:
      containers:
      - image: tanzuharbor.tanzu.lab/app-images/pet-clinic@sha256:deeea2bfc8bfa4e3e9338fe7706369563446acfc08eb2aeeca658e7ca5c100af
        name: pet-clinic
        resources: {}
status: {}
