apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: se-spring-boot
  name: se-spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: se-spring-boot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: se-spring-boot
    spec:
      containers:
      - image: tbsregistry.tanzu.lab/tbs-project/spring-images/pet-clinic@sha256:c2cce060c0517174e51890c0a9700abb9311991ec97479959379944af352f2ef
        name: pet-clinic
        resources: {}
status: {}
