apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: se-spring-boot
  name: se-spring-boot
  namespace: se-spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: se-spring-boot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: se-spring-boot
    spec:
      containers:
      - image: tbsregistry.tanzu.lab/tbs-project/spring-images/pet-clinic@sha256:50eaaeeb33afe9991ea0cb17dcce909cd70e8d9beb8f29f1142022b053fd7b57
        name: pet-clinic
        resources: {}
status: {}
