apiVersion: apps/v1
kind: Deployment
metadata:
  name: vac-mysql
  labels:
    app: vac-mysql
spec:
  replicas: 1
  template:
    metadata:
      name: vac-mysql
      labels:
        app: vac-mysql
    spec:
      containers:
        - name: vac-mysql
          image: tanzuharbor.tanzu.lab/appcatalog-ns/centos-7/mysql@sha256:a18a7783691216a66458e045bcb2d35ab0c4888bab7d15cb2a5caa07d2da63c6
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: vac-mysql
