apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: se-spring-boot
  name: se-spring-boot
  namespace: se-spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: se-spring-boot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: se-spring-boot
    spec:
      containers:
      - image: tbsregistry.tanzu.lab/tbs-project/spring-images/pet-clinic@sha256:851d49d1a9786d6b3fa17fa5d669dbbb687e23d047e6c08165d629603f0d70ec
        name: pet-clinic
        resources: {}
status: {}
